# -*- coding: utf-8 -*-
"""
/***************************************************************************
 cats
                                 A QGIS plugin
 Gato guardian
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-08-21
        copyright            : (C) 2023 by nemo
        email                : nemo@sea.co
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
 
from qgis.PyQt.QtGui import *
from qgis.PyQt.QtCore import *
from qgis.gui import QgsProjectionSelectionDialog


def setProjectCrs():
    dialog = QgsProjectionSelectionDialog()
    if dialog.exec_():
        crs = dialog.crs()
        QgsProject.instance().setCrs(crs)

# noinspection PyPep8Naming
def classFactory(iface):     
    '''  return  '''
    ProjectCrsPlugin(iface)
      
    from .CatWatch import cats
    return cats(iface)

 
class ProjectCrsPlugin:
    def __init__(self, iface):
        self.iface = iface        
        iface.newProjectCreated.connect(setProjectCrs)
 
    def initGui(self):
        pass
 
    def unload(self):
        self.iface.newProjectCreated.disconnect(setProjectCrs)